@startuml
'https://plantuml.com/class-diagram

class ATMContext{
    - ATMState state;
    - int currentBalance;
    - int maxWithDrawLimit;
    + ATMContext(int initialBalance, int maxWithDrawLimit)
    + setState(ATMState state)
    + withDraw(int amout)
}

interface ATMState{
    + withDraw(ATMContext context,int amout)
}

class ReadyState{
}

class LimitedCashState{
}

class NoCashState{
}

ATMContext --> ATMState: currentState
ATMState <|.. ReadyState
ATMState <|.. LimitedCashState
ATMState <|.. NoCashState

@enduml