@startuml
'https://plantuml.com/class-diagram

interface SetImplementator<T>{
    + void add(T data)
    + T get(int i)
    + remove(int index)
}

abstract class SequenceAbstraction<T>{
    + void push(T data)
    + void T pop()
    + void clear()
}

SequenceAbstraction --> "imp" SetImplementator
SetImplementator <|.. MyArray
SetImplementator <|.. MyList

SequenceAbstraction <|-- MyStack
SequenceAbstraction <|-- MyQueue
@enduml