@startuml
'https://plantuml.com/class-diagram

class Book {
    String tuaDe,tacgia;
    int soTrang;
    List<String> danhSachCacChuong;
    # Book(Buider b)
    + String toString()
}

class Builder {
    String tuaDe,tacgia;
    int soTrang;
    List<String> danhSachCacChuong;
    + Builder buildTuaDe(String tuaDe)
    + Builder buildSoTrang(int soTrang)
    + Builder buildTacGia(String tacGia)
    + Builder buildDanhSachCacChuong(String chuong)
    + Book buildBook()
}

Builder ..> Book

@enduml