@startuml
'https://plantuml.com/class-diagram

interface Observer{
    + void update(float exchangeRate);
}

interface Subject{
    + void addObserver(Observer observer)
    + void removeObserver(Observer observer)
    + void notifyObserver();
}

class TiGia {
    - List<Observer> observers;
    - float exchangeRate;
    + setExchangeRate(float exchangeRate)
}

class NhaDauTu {
    - String name
    + NhaDauTu(String name)
}

Observer <|.. NhaDauTu
Subject <|.. TiGia
TiGia --> Observer : Thông báo
@enduml