@startuml
'https://plantuml.com/class-diagram

class Computer{
    String cpu,ram,rom,storage;
    # Computer (Builder b);
    + String toString();
}

class Builder {
    String cpu,ram,rom,storage;
    + Builder buidCPU(String cpu);
    + Builder buildRAM(String ram);
    + Builder buildROM(String rom);
    + Builder buildStorage(String storage);
    + Computer build()
}

Builder ..> Computer

@enduml